/*
 * Rika Firenet - OpenAPI 3.0
 *
 * Rika Firenet API operations
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoveFeatures {
    #[serde(rename = "airFlaps")]
    pub air_flaps: bool,
    #[serde(rename = "bakeMode")]
    pub bake_mode: bool,
    #[serde(rename = "insertionMotor")]
    pub insertion_motor: bool,
    #[serde(rename = "logRuntime")]
    pub log_runtime: bool,
    #[serde(rename = "multiAir1")]
    pub multi_air1: bool,
    #[serde(rename = "multiAir2")]
    pub multi_air2: bool,
}

impl StoveFeatures {
    pub fn new(
        air_flaps: bool,
        bake_mode: bool,
        insertion_motor: bool,
        log_runtime: bool,
        multi_air1: bool,
        multi_air2: bool,
    ) -> StoveFeatures {
        StoveFeatures {
            air_flaps,
            bake_mode,
            insertion_motor,
            log_runtime,
            multi_air1,
            multi_air2,
        }
    }
}
